---
title: "Capstone Project"
output:
  pdf_document: default
  html_notebook: default
  html_document:
    df_print: paged
---



```{r}
#In this project we'll work with some data and with the goal of trying to find replacement players for the ones lost at the start of the off-season - During the 2001-02 offseason, the team lost three key free agents to larger market teams: 2000 AL MVP Jason Giambi to the New York Yankees, outfielder Johnny Damon to the Boston Red Sox, and closer Jason Isringhausen to the St. Louis Cardinals.

batting <- read.csv('Batting.csv')
```
```{r}
head(batting)
```

```{r}
str(batting)
```

```{r}
head(batting$AB)
```

```{r}
head(batting$X2B)
```

```{r}
#Getting Batting average
batting$BA <- batting$H / batting$AB
```

```{r}
tail(batting$BA,5)
```

```{r}
# On Base Percentage
batting$OBP <- (batting$H + batting$BB + batting$HBP)/(batting$AB + batting$BB + batting$HBP + batting$SF)
```

```{r}
# Creating X1B (Singles)
batting$X1B <- batting$H - batting$X2B - batting$X3B - batting$HR
```

```{r}
# Creating Slugging Average (SLG)
batting$SLG <- ((1 * batting$X1B) + (2 * batting$X2B) + (3 * batting$X3B) + (4 * batting$HR) ) / batting$AB
```

```{r}
#Checking structure of new columns
str(batting)
```

```{r}
sal <- read.csv('Salaries.csv')
```

```{r}
#Use summary to get a summary of the batting data frame and notice the minimum year in the yearID column. Our batting data goes back to 1871! Our salary data starts at 1985, meaning we need to remove the batting data that occured before 1985.
#Use subset() to reassign batting to only contain data from 1985 and onwards
batting <- subset(batting,yearID >= 1985)
summary(batting)
```

```{r}
#Using the merge() function to merge the batting and sal data frames by c('playerID','yearID'). Call the new data frame combo
combo <- merge(batting,sal,by=c('playerID','yearID'))
summary(combo)

```

```{r}
#Analyzing the Lost Players
#The Oakland A's lost 3 key players during the off-season. We'll want to get their stats to see what we have to replace. The players lost were: first baseman 2000 AL MVP Jason Giambi (giambja01) to the New York Yankees, outfielder Johnny Damon (damonjo01) to the Boston Red Sox and infielder Rainer Gustavo "Ray" Olmedo ('saenzol01').
lost_players <- subset(combo,playerID %in% c('giambja01','damonjo01','saenzol01') )
lost_players <- subset(lost_players,yearID == 2001)
lost_players
```

```{r}
#Reduce the lost_players data frame to the following columns: playerID,H,X2B,X3B,HR,OBP,SLG,BA,AB

lost_players <- lost_players[,c('playerID','H','X2B','X3B','HR','OBP','SLG','BA','AB')]
head(lost_players)
```

```{r}
#Replacement Players
#Now we have all the information we need!Now we find Replacement Players for the key three players we lost, we have three constraints:

#The total combined salary of the three players can not exceed 15 million dollars.
#Their combined number of At Bats (AB) needs to be equal to or greater than the lost players.
#Their mean OBP had to equal to or greater than the mean OBP of the lost players
library(dplyr)
avail.players <- filter(combo,yearID==2001)

library(ggplot2)
ggplot(avail.players,aes(x=OBP,y=salary)) + geom_point()
```

```{r}
#Looks like there is no point in paying above 8 million or so (I'm just eyeballing this number). I'll choose that as a cutt off point. There are also a lot of players with OBP==0. Let's get rid of them too.
avail.players <- filter(avail.players,salary<8000000,OBP>0)
avail.players <- filter(avail.players,AB >= 500)

possible <- head(arrange(avail.players,desc(OBP)),10)

possible <- possible[,c('playerID','OBP','AB','salary')]

possible
```

```{r}
possible[2:4,]     #Can't choose giambja again, but the other ones look good (2-4). I choose them
```


