---
title: "Logistic Regression"
output:
  pdf_document: default
  html_document:
    df_print: paged
---



```{r}
#In this project we will be working with the UCI adult dataset. We will be attempting to predict if people in the data set belong in a certain class by salary, either making <=50k or >50k per year.

setwd('C:/Users/admin/Desktop/R/R-Course-HTML-Notes/R-for-Data-Science-and-Machine-Learning/Training Exercises/Machine Learning Projects/CSV files for ML Projects')

adult <- read.csv('adult_sal.csv')

head(adult)
```

```{r}
#The index has been repeated, so we drop this column.

library(dplyr)
adult <- select(adult,-X)

head(adult)
```

```{r}
str(adult)
```

```{r}
summary(adult)
```

```{r}
#Notice that we have a lot of columns that are cateogrical factors, however a lot of these columns have too many factors than may be necessary. In this data cleaning section we'll try to clean these columns up by reducing the number of factors.

#type_employer column

table(adult$type_employer)
```

```{r}
#Combine never-worked and without-pay into a single group called "Unemployed".
unemp <- function(job){
    job <- as.character(job)
    if (job=='Never-worked' | job=='Without-pay'){
        return('Unemployed')
    }else{
        return(job)
    }
}

adult$type_employer <- sapply(adult$type_employer,unemp)

table(adult$type_employer)
```

```{r}
#Combine State and Local gov jobs into a category called SL-gov and combine self-employed jobs into a category called self-emp.

group_emp <- function(job){
    if (job=='Local-gov' | job=='State-gov'){
        return('SL-gov')
    }else if (job=='Self-emp-inc' | job=='Self-emp-not-inc'){
        return('self-emp')
    }else{
        return(job)
    }
}

adult$type_employer <- sapply(adult$type_employer,group_emp)

table(adult$type_employer)
```

```{r}
#Marital Column

table(adult$marital)
```

```{r}
#Reduce this to three groups:
#Married
#Not-Married
#Never-Married

group_marital <- function(mar){
    mar <- as.character(mar)
    
    # Not-Married
    if (mar=='Separated' | mar=='Divorced' | mar=='Widowed'){
        return('Not-Married')
    
    # Never-Married   
    }else if(mar=='Never-married'){
        return(mar)
    
     #Married
    }else{
        return('Married')
    }
}

adult$marital <- sapply(adult$marital,group_marital)
table(adult$marital)
```

```{r}
Asia <- c('China','Hong','India','Iran','Cambodia','Japan', 'Laos' ,
          'Philippines' ,'Vietnam' ,'Taiwan', 'Thailand')

North.America <- c('Canada','United-States','Puerto-Rico' )

Europe <- c('England' ,'France', 'Germany' ,'Greece','Holand-Netherlands','Hungary',
            'Ireland','Italy','Poland','Portugal','Scotland','Yugoslavia')

Latin.and.South.America <- c('Columbia','Cuba','Dominican-Republic','Ecuador',
                             'El-Salvador','Guatemala','Haiti','Honduras',
                             'Mexico','Nicaragua','Outlying-US(Guam-USVI-etc)','Peru',
                            'Jamaica','Trinadad&Tobago')
Other <- c('South')
```

```{r}
group_country <- function(ctry){
    if (ctry %in% Asia){
        return('Asia')
    }else if (ctry %in% North.America){
        return('North.America')
    }else if (ctry %in% Europe){
        return('Europe')
    }else if (ctry %in% Latin.and.South.America){
        return('Latin.and.South.America')
    }else{
        return('Other')      
    }
}

```

```{r}
adult$country <- sapply(adult$country,group_country)
```

```{r}
table(adult$country)
```

```{r}
#Changing data type to factor

adult$type_employer <- sapply(adult$type_employer,factor)
adult$country <- sapply(adult$country,factor)
adult$marital <- sapply(adult$marital,factor)

str(adult)
```

```{r}
#Missing Data


library(Amelia)
```

```{r}
#Convert any cell with a '?' or a ' ?' value to a NA value
adult[adult == '?'] <- NA
```

```{r}
adult$type_employer <- sapply(adult$type_employer,factor)
adult$country <- sapply(adult$country,factor)
adult$marital <- sapply(adult$marital,factor)
adult$occupation <- sapply(adult$occupation,factor)
```

```{r}
#Using missmap to check missing values
missmap(adult,y.at=c(1),y.labels = c(''),col=c('yellow','black'))
```

```{r}
#Use na.omit() to omit NA data from the adult data frame. Note, it really depends on the situation and your data to judge whether or not this is a good decision. You shouldn't always just drop NA values.

adult <- na.omit(adult)
```

```{r}
missmap(adult,y.at=c(1),y.labels = c(''),col=c('yellow','black'))
```

```{r}
#Although we've cleaned the data, we still have explored it using visualization.
library(ggplot2)
library(dplyr)
ggplot(adult,aes(age)) + geom_histogram(aes(fill=income),color='black',binwidth=1) + theme_bw()
```

```{r}
#Plot a histogram of hours worked per week

ggplot(adult,aes(hr_per_week)) + geom_histogram() + theme_bw()
```

```{r}
#Rename the country column to region column to better reflect the factor levels.
names(adult)[names(adult)=="country"] <- "region"

ggplot(adult,aes(region)) + geom_bar(aes(fill=income),color='black')+theme_bw()+
theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

```{r}
#Building a model

#TrainTest Split

library(caTools)


set.seed(101) 


sample <- sample.split(adult$income, SplitRatio = 0.70) # SplitRatio = percent of sample==TRUE


train = subset(adult, sample == TRUE)


test = subset(adult, sample == FALSE)
```

```{r}
#Use all the features to train a glm() model on the training data set, pass the argument family=binomial(logit) into the glm function.

model = glm(income ~ ., family = binomial(logit), data = train)
summary(model)
```

```{r}
#Using step
new.step.model <- step(model)
```

```{r}
summary(new.step.model)
```

```{r}
#You should have noticed that the step() function kept all the features used previously

test$predicted.income = predict(model, newdata=test, type="response")

table(test$income, test$predicted.income > 0.5)

```

```{r}
#recall
6732/(6372+548)

#precision
6732/(6372+872)
```


